[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
FastLapackInterface = "29a986be-02c6-4525-aec4-84b980013641"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticKernels = "4c63dfa8-a427-4548-bd2f-4c19e87a7dc7"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
